[api_keys]
gemini="AIzaSyCnAELx_6xFF-fkxPkHC53IxRE5QOsEs54"
openai = "YOUR_OPENAI_API_KEY"

[database]
host = "localhost"
port = 5432
user = "your_username"
password = "your_password"
database = "your_db_name"
